package pl.jblew.doing;

import picocli.CommandLine;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Doing {

    public Doing() {
        
    }

    public void start(String [] args) {
        
    }
        
    public static void main(String[] args) {
        CommandLine.run(new Doing(), System.out, args);
    }
}
