package pl.jblew.doing;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import pl.jblew.doing.Doing;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
    }
}
